name: Build release zip

on:
  release:
    types: [published]

jobs:
  build:
    name: Build release zip
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node
      uses: actions/setup-node@v4

    - name: Checkout
      uses: actions/checkout@v4

    - name: Build Zip
      working-directory: wp-content/plugins/pearl
      run: |
        npm install
        npm run build
        npm run plugin-zip

    - name: Unzip the archive (prevents double zip problem)
      run: unzip wp-content/plugins/pearl/pearl.zip -d zipfile

    - name: Upload release zip
      uses: actions/upload-artifact@v4
      with:
        name: BigSpark-Pearl
        path: zipfile
