name: Build release zip

on:
  release:
    types: [published]

jobs:
  build:
    name: Build release zip
    runs-on: ubuntu-latest

    env:
      TAG_NAME: ${{ github.event.release.tag_name }}
      REPO:     ${{ github.repository }}
      S3_BUCKET: composer-packages
      S3_BASE_URL: https://t56v2.upcloudobjects.com
      S3_PREFIX: composer-repo

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Node
      uses: actions/setup-node@v4

    - name: Build Pearl
      working-directory: wp-content/plugins/pearl
      run: |
        npm install
        npm run build
        npm run plugin-zip

    - name: Update composer.json dist info
      run: |
        # strip 'v' for semver-version
        VERSION=${TAG_NAME#v}

        # write new json
        jq --arg v "$VERSION" \
           --arg url "$S3_BASE_URL/$S3_BUCKET/$S3_PREFIX/p/bigsparkit/pearl/$VERSION/pearl-$VERSION.zip" \
           '
             .version = $v
             | .dist = {type:"zip",url:$url}
             | del(.config)
             | del(.repositories)
           ' composer.json > composer.json.tmp

        mv composer.json.tmp composer.json

    - name: Install rclone
      run: |
        curl https://rclone.org/install.sh | sudo bash

        # Configureer rclone voor UpCloud
        mkdir -p ~/.config/rclone
        cat > ~/.config/rclone/rclone.conf << EOF
        [upcloud]
        type = s3
        provider = Other
        access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        endpoint = ${{ env.S3_BASE_URL }}
        EOF

    - name: Upload to S3 using rclone
      run: |
        VERSION=${TAG_NAME#v}

        # Create directories
        mkdir -p "p/bigsparkit/pearl/$VERSION"
        cp composer.json "p/bigsparkit/pearl/$VERSION/"
        cp wp-content/plugins/pearl/pearl.zip "p/bigsparkit/pearl/$VERSION/pearl-$VERSION.zip"

        # Upload to S3
        rclone copy "p/bigsparkit/pearl/$VERSION" upcloud:$S3_BUCKET/$S3_PREFIX/p/bigsparkit/pearl/$VERSION --progress

        # Download packages.json - alternatieve aanpak
        echo "Checking if packages.json exists on S3..."
        if rclone cat upcloud:$S3_BUCKET/$S3_PREFIX/packages.json > packages.json 2>/dev/null; then
          echo "Found and downloaded packages.json. File size:"
          ls -la packages.json
        else
          echo "packages.json not found on S3, creating empty file..."
          echo '{"packages":{}}' > packages.json
          echo "Empty packages.json created. File size:"
          ls -la packages.json
        fi

        # Update packages.json with new version
        jq --arg v "$VERSION" \
           --arg url "$S3_BASE_URL/$S3_BUCKET/$S3_PREFIX/p/bigsparkit/pearl/$VERSION/pearl-$VERSION.zip" \
           '
           .packages."bigsparkit/pearl"[$v] = {
             "name": "bigsparkit/pearl",
             "version": $v,
             "type": "wordpress-plugin",
             "dist": {
               "type": "zip",
               "url": $url
             },
             "require": {
               "php": ">=8.2"
             },
             "extra": {
               "installer-name": "pearl"
             }
           }
           ' packages.json > packages.json.tmp

        mv packages.json.tmp packages.json

        # Upload updated packages.json to S3
        rclone copyto packages.json upcloud:$S3_BUCKET/$S3_PREFIX/packages.json

    - name: Commit dist metadata in tag
      run: |
        git config --local user.name "GitHub Actions"
        git config --local user.email "[email protected]"

        git add composer.json
        git commit -m "🔖  Add build assets & dist metadata for $TAG_NAME"

        git tag -f "$TAG_NAME" -m "Release $TAG_NAME (with assets & dist metadata)"

        git push --force origin "$TAG_NAME"

    - name: Upload pearl.zip to GitHub release
      run: |
        gh release upload "$TAG_NAME" wp-content/plugins/pearl/pearl.zip --clobber
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
